path:
  server: config/clusters
  api: config/apis
  access_log:
  log:
  user: config/users
  role: config/roles

system:
  auth_redis:
        address: 127.0.0.1
        db: 1
        expire: 7200

